"""
Django settings for sahara_gold project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'dev-only-change-me-before-deployment')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = [host.strip() for host in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if host.strip()]

# Auto-detect Render external hostname
render_external_hostname = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if render_external_hostname and render_external_hostname not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(render_external_hostname)

# Support wildcard onrender.com in allowed hosts if on Render
if os.getenv('RENDER') and '.onrender.com' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('.onrender.com')

CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app',
    'https://*.ngrok.io',
    'https://pei-baddish-bruce.ngrok-free.dev',
    'https://*.onrender.com',
]

extra_csrf = [origin.strip() for origin in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if origin.strip()]
CSRF_TRUSTED_ORIGINS.extend(extra_csrf)

if render_external_hostname:
    render_origin = f'https://{render_external_hostname}'
    if render_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(render_origin)

# Ngrok/Proxy Settings
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# CSRF_COOKIE_SECURE = True # Uncomment if you forced HTTPS
# SESSION_COOKIE_SECURE = True # Uncomment if you forced HTTPS



# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party
    'rest_framework',
    'corsheaders',
    # 'sslserver', # Removed as we are back to localhost HTTP
    # Local apps
    'products',
    'orders',
    'rates',
    'payments',
    'cms',
    'ai',
    'core',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.TenantMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sahara_gold.urls'

FRONTEND_DIR = BASE_DIR.parent / 'frontend' / 'dist'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [FRONTEND_DIR] if FRONTEND_DIR.exists() else [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sahara_gold.wsgi.application'


# PostgreSQL database configuration (supports Render DATABASE_URL & local settings)
database_url = os.getenv('DATABASE_URL')
if database_url:
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.config(
            default=database_url,
            conn_max_age=int(os.getenv('DB_CONN_MAX_AGE', '600')),
            conn_health_checks=True,
            ssl_require=not DEBUG,
        )
    }
else:
    if os.getenv('DATABASE_ENGINE', 'postgresql').lower() != 'postgresql':
        raise RuntimeError('Sahara Gold requires PostgreSQL; SQLite is not supported.')

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'sahara_gold'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
            'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '60')),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [FRONTEND_DIR] if FRONTEND_DIR.exists() else []
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
WHITENOISE_MANIFEST_STRICT = False


# Media Files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# API response cache. Use Redis in multi-process production deployments and
# local memory for development when REDIS_URL is not configured.
REDIS_URL = os.getenv('REDIS_URL', '').strip()
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
            'TIMEOUT': 300,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'sahara-gold-api-cache',
            'TIMEOUT': 300,
        }
    }

# CORS Settings
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in os.getenv(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173,http://localhost:5174,http://127.0.0.1:5174',
).split(',') if origin.strip()]

# Allow Render & Ngrok origins for CORS
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.onrender\.com$",
] if not DEBUG else [
    r"^https://.*\.ngrok-free\.app$",
    r"^https://.*\.ngrok\.io$",
    r"^https://.*\.onrender\.com$",
]

frontend_url = os.getenv('FRONTEND_URL', '').strip()
if frontend_url and frontend_url not in CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS.append(frontend_url)
if frontend_url and frontend_url.startswith('https://') and frontend_url not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append(frontend_url)

from datetime import timedelta

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30 if not DEBUG else 60 * 24 * 7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7 if not DEBUG else 30),
    'ROTATE_REFRESH_TOKENS': not DEBUG,
    'BLACKLIST_AFTER_ROTATION': not DEBUG,
}

from corsheaders.defaults import default_headers
CORS_ALLOW_HEADERS = list(default_headers) + [
    'X-Tenant-Slug',
    'ngrok-skip-browser-warning',
]

PHONE_NUMBER_ID = os.getenv('PHONE_NUMBER_ID', '1045948881940344')
WHATSAPP_TOKEN = os.getenv('WHATSAPP_TOKEN', '')
META_APP_SECRET = os.getenv('META_APP_SECRET', '')

# --- App Settings ---

FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')
BACKEND_URL = os.getenv('BACKEND_URL', 'http://localhost:8000')
DEFAULT_TENANT_SLUG = os.getenv('DEFAULT_TENANT_SLUG', 'sahara-gold')
INVOICE_LINK_MAX_AGE = int(os.getenv('INVOICE_LINK_MAX_AGE', str(7 * 24 * 60 * 60)))

# Payment Gateway Configuration (SSLCommerz)
SSLCOMMERZ_STORE_ID = os.getenv('SSLCOMMERZ_STORE_ID', 'testbox')
SSLCOMMERZ_STORE_PASS = os.getenv('SSLCOMMERZ_STORE_PASS', 'qwerty')
SSLCOMMERZ_IS_SANDBOX = os.getenv('SSLCOMMERZ_IS_SANDBOX', 'True') == 'True'

# Legacy bKash (Optional/Reference)
BKASH_BASE_URL = os.getenv('BKASH_BASE_URL', 'https://tokenized.sandbox.bka.sh/v1.2.0-beta')

# JAZZMIN Settings (CMS)
JAZZMIN_SETTINGS = {
    "site_title": "Sahara Gold Admin",
    "site_header": "Sahara Gold",
    "site_brand": "Sahara Gold",
    "welcome_sign": "Welcome back",
    "copyright": "Sahara Gold Ltd",
    "search_model": "products.Product",
    "show_ui_builder": True,
}

# Email Backend
# Email Backend - Safe fallback to console backend if SMTP password is not set
EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.smtp.EmailBackend' if os.getenv('EMAIL_HOST_PASSWORD') else 'django.core.mail.backends.console.EmailBackend'
)
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '465'))
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'True').lower() == 'true'
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'False').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'saharagold19@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'Sahara Gold <saharagold19@gmail.com>')
STORE_EMAIL = os.getenv('STORE_EMAIL', 'saharagold19@gmail.com')
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', '25'))
RESEND_API_KEY = os.getenv('RESEND_API_KEY', '').strip()
RESEND_FROM_EMAIL = os.getenv('RESEND_FROM_EMAIL', DEFAULT_FROM_EMAIL)

if EMAIL_USE_TLS and EMAIL_USE_SSL:
    raise RuntimeError('EMAIL_USE_TLS and EMAIL_USE_SSL cannot both be enabled.')

if EMAIL_BACKEND.endswith('smtp.EmailBackend'):
    if not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
        import warnings
        warnings.warn('EMAIL_HOST_PASSWORD not configured; falling back to console email backend.')
        EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    elif not DEFAULT_FROM_EMAIL or not STORE_EMAIL:
        raise RuntimeError('SMTP email backend requires DEFAULT_FROM_EMAIL and STORE_EMAIL.')

# AI / LLM Configuration
HUGGINGFACE_API_KEY = os.getenv('HUGGINGFACE_API_KEY', '')
AI_MODEL = os.getenv('AI_MODEL', '')
STORE_NAME = os.getenv('STORE_NAME', '')
STORE_PHONE = os.getenv('STORE_PHONE', '')
STORE_WHATSAPP = os.getenv('STORE_WHATSAPP', '')
STORE_ADDRESS = os.getenv('STORE_ADDRESS', '')
WEBHOOK_VERIFY_TOKEN = os.getenv('WEBHOOK_VERIFY_TOKEN', '')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

if not DEBUG:
    if not SECRET_KEY or len(SECRET_KEY) < 20 or SECRET_KEY == 'dev-only-change-me-before-deployment':
        import secrets
        SECRET_KEY = secrets.token_urlsafe(50)

    if not ALLOWED_HOSTS:
        ALLOWED_HOSTS = ['.onrender.com', 'localhost', '127.0.0.1']

    if not CORS_ALLOWED_ORIGINS and not CORS_ALLOWED_ORIGIN_REGEXES:
        CORS_ALLOWED_ORIGIN_REGEXES = [r"^https://.*\.onrender\.com$"]

    if FRONTEND_URL and not FRONTEND_URL.startswith('https://') and not FRONTEND_URL.startswith('http://localhost'):
        import warnings
        warnings.warn('Production FRONTEND_URL should use HTTPS.')

    if BACKEND_URL and not BACKEND_URL.startswith('https://') and not BACKEND_URL.startswith('http://localhost') and not BACKEND_URL.startswith('http://127.0.0.1'):
        import warnings
        warnings.warn('Production BACKEND_URL should use HTTPS.')

    if SSLCOMMERZ_IS_SANDBOX and os.getenv('ALLOW_SANDBOX_PAYMENTS', 'False').lower() != 'true':
        raise RuntimeError('Production SSLCommerz must not use sandbox mode (set ALLOW_SANDBOX_PAYMENTS=True to override for testing).')

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

