# Generated by Django 6.0.1 on 2026-01-30 10:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoldRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('rate_22k', models.IntegerField(help_text='Price per gram for 22K')),
                ('rate_21k', models.IntegerField(help_text='Price per gram for 21K')),
                ('rate_18k', models.IntegerField(help_text='Price per gram for 18K')),
                ('rate_traditional', models.IntegerField(help_text='Price per gram for Traditional Gold')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
