# Generated by Django 5.2.17 on 2026-09-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_alter_goldrate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldrate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
