#!/usr/bin/env python3
"""
Sahara Gold - Production Readiness Verification Script
Run from gold-shop/ directory: python scripts/verify_production_readiness.py
Exit code 0 = all checks passed. Non-zero = failures found.
"""
import os, re, sys, json, subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BACKEND = ROOT / "backend"
FRONTEND = ROOT / "frontend"
RENDER_YAML = ROOT / "render.yaml"
REQUIREMENTS = BACKEND / "requirements.txt"
SETTINGS_FILE = BACKEND / "sahara_gold" / "settings.py"
FRONTEND_DIST = FRONTEND / "dist"
FRONTEND_INDEX = FRONTEND_DIST / "index.html"

failures = []
warnings = []

def ok(msg): print(f"  [PASS]  {msg}")
def fail(msg):
    print(f"  [FAIL]  {msg}")
    failures.append(msg)
def warn(msg):
    print(f"  [WARN]  {msg}")
    warnings.append(msg)
def section(title):
    print(f"\n{'='*60}\n  {title}\n{'='*60}")


def check_render_yaml():
    section("1. render.yaml - Blueprint Integrity")
    if not RENDER_YAML.exists():
        fail("render.yaml not found at project root"); return
    text = RENDER_YAML.read_text(encoding="utf-8")
    ok("render.yaml present")
    if "healthCheckPath: /api/health/" in text: ok("healthCheckPath = /api/health/")
    else: fail("healthCheckPath missing (expected /api/health/)")
    if "sahara-gold-backend" in text: ok("Backend service declared")
    else: fail("Backend service 'sahara-gold-backend' not found")
    if "sahara-gold-frontend" in text: ok("Frontend static site declared")
    else: fail("Frontend static site 'sahara-gold-frontend' not found")
    if "sahara-gold-db" in text: ok("Database declared")
    else: fail("Database 'sahara-gold-db' not found")
    if "rewrite" in text and "index.html" in text: ok("SPA rewrite rules present")
    else: warn("SPA rewrite rules not found - React Router may break on page refresh")
    if "fromDatabase" in text and "connectionString" in text: ok("DATABASE_URL wired from database service")
    else: fail("DATABASE_URL not wired from database")
    if "generateValue: true" in text: ok("SECRET_KEY auto-generated by Render")
    else: warn("SECRET_KEY not using generateValue")
    if 'key: DEBUG' in text and '"False"' in text: ok("DEBUG=False in render.yaml")
    else: warn("DEBUG value not confirmed as False in render.yaml - verify in dashboard")
    if "ALLOWED_HOSTS" in text and ".onrender.com" in text: ok("ALLOWED_HOSTS includes .onrender.com wildcard")
    else: fail("ALLOWED_HOSTS missing or does not include .onrender.com")
    if "CORS_ALLOWED_ORIGINS" in text: ok("CORS_ALLOWED_ORIGINS configured")
    else: warn("CORS_ALLOWED_ORIGINS not set")

SYNC_FALSE_KEYS = {"RESEND_API_KEY", "APISED_API_KEY"}

def check_secret_hygiene():
    section("2. Secret Hygiene - No Committed Secrets")
    render_text = RENDER_YAML.read_text(encoding="utf-8") if RENDER_YAML.exists() else ""
    for key in SYNC_FALSE_KEYS:
        pattern = re.compile(rf'- key: {re.escape(key)}.*?(?=- key:|\Z)', re.DOTALL)
        match = pattern.search(render_text)
        if match:
            block = match.group(0)
            if "sync: false" in block: ok(f"{key} correctly marked sync:false (dashboard-managed)")
            elif "value:" in block: fail(f"{key} has a hardcoded value in render.yaml!")
            else: warn(f"{key} found but sync mode unclear")
        else:
            warn(f"{key} not found in render.yaml - ensure it is set in Render dashboard")
    try:
        result = subprocess.run(["git","ls-files","--error-unmatch","backend/.env"],
                                capture_output=True, cwd=str(ROOT))
        if result.returncode == 0: fail("backend/.env is tracked by git - add to .gitignore!")
        else: ok("backend/.env is NOT tracked by git")
    except FileNotFoundError:
        warn("git not found - skipping git-tracked file check")
    gitignore = ROOT / ".gitignore"
    if gitignore.exists():
        gi_text = gitignore.read_text(encoding="utf-8")
        if ".env" in gi_text: ok(".gitignore includes .env pattern")
        else: fail(".gitignore does NOT include .env - secrets could be committed!")
    else:
        warn(".gitignore not found at project root")
    if re.search(r're_[A-Za-z0-9]{20,}', render_text):
        warn("Potential Resend live API key found in render.yaml - verify it is not a live secret")
    else:
        ok("No raw Resend live API key detected in render.yaml")


def check_django_settings():
    section("3. Django Settings - Production Readiness")
    if not SETTINGS_FILE.exists():
        fail(f"settings.py not found at {SETTINGS_FILE}"); return
    text = SETTINGS_FILE.read_text(encoding="utf-8")
    # SECRET_KEY - check for os.getenv / os.environ usage
    if re.search(r'SECRET_KEY\s*=\s*os\.(getenv|environ)', text):
        ok("SECRET_KEY read from environment variable (os.getenv/os.environ)")
    elif "SECRET_KEY" in text:
        warn("SECRET_KEY pattern found but env read unclear - inspect settings.py")
    # DEBUG - check for os.getenv / bool parsing
    if re.search(r'DEBUG\s*=\s*os\.(getenv|environ)', text):
        ok("DEBUG read from environment variable (os.getenv/os.environ)")
    elif re.search(r'DEBUG\s*=\s*False', text):
        ok("DEBUG hardcoded to False")
    elif re.search(r'DEBUG\s*=\s*True', text):
        fail("DEBUG is hardcoded to True - security risk in production!")
    else:
        warn("DEBUG configuration unclear - verify it is False in production")
    if "dj_database_url" in text or "DATABASE_URL" in text: ok("Database configured via DATABASE_URL / dj-database-url")
    else: warn("No DATABASE_URL pattern found in settings - Postgres connection may fail on Render")
    if "STATIC_ROOT" in text: ok("STATIC_ROOT configured (required for collectstatic)")
    else: fail("STATIC_ROOT not configured - collectstatic will fail")
    if "whitenoise" in text.lower() or "WhiteNoise" in text: ok("WhiteNoise static file middleware found")
    else: warn("No WhiteNoise middleware found - static files may not serve correctly")
    if "corsheaders" in text or "CORS_ALLOWED_ORIGINS" in text: ok("CORS configured in settings")
    else: warn("CORS not configured - frontend API calls may be blocked")
    if REQUIREMENTS.exists():
        req_text = REQUIREMENTS.read_text(encoding="utf-8")
        # psycopg2 OR psycopg (v3) are both valid PostgreSQL drivers
        has_postgres = "psycopg2" in req_text or "psycopg" in req_text
        if has_postgres: ok("requirements.txt includes PostgreSQL driver (psycopg2 or psycopg v3)")
        else: fail("requirements.txt missing PostgreSQL driver (psycopg2 or psycopg)")
        for dep, purpose in [("gunicorn","WSGI server"),("dj-database-url","DATABASE_URL parsing"),("whitenoise","Static file serving")]:
            if dep in req_text: ok(f"requirements.txt includes '{dep}' ({purpose})")
            else: fail(f"requirements.txt missing '{dep}' - needed for: {purpose}")
    else:
        fail("requirements.txt not found")


def check_frontend_build():
    section("4. Frontend Build - Artifacts Present")
    if not FRONTEND.exists():
        fail("frontend/ directory not found"); return
    if FRONTEND_DIST.exists(): ok("frontend/dist/ directory exists")
    else:
        warn("frontend/dist/ not found - run npm run build before deploying (Render builds automatically)"); return
    if FRONTEND_INDEX.exists(): ok("frontend/dist/index.html present")
    else: fail("frontend/dist/index.html missing - SPA will not render")
    assets_dir = FRONTEND_DIST / "assets"
    if assets_dir.exists():
        js_files = list(assets_dir.glob("*.js"))
        css_files = list(assets_dir.glob("*.css"))
        ok(f"Assets: {len(js_files)} JS bundle(s), {len(css_files)} CSS file(s)")
        if not js_files: fail("No JS bundles found in dist/assets - build may have failed")
    else:
        warn("dist/assets/ not found")
    pkg = FRONTEND / "package.json"
    if pkg.exists():
        data = json.loads(pkg.read_text(encoding="utf-8"))
        scripts = data.get("scripts", {})
        if "build" in scripts: ok(f"package.json build script: {scripts['build']}")
        else: fail("package.json missing build script - Render build will fail")
    else:
        fail("frontend/package.json not found")


def check_build_script():
    section("5. Backend build.sh - Render Build Command")
    build_sh = BACKEND / "build.sh"
    if not build_sh.exists():
        fail("backend/build.sh not found - Render build will fail"); return
    ok("backend/build.sh present")
    text = build_sh.read_text(encoding="utf-8")
    for cmd, label in [("pip install","pip install step"),("migrate","Django migrations"),("collectstatic","Static file collection")]:
        if cmd in text: ok(f"build.sh includes: {label}")
        else: fail(f"build.sh missing: {label}")


def check_health_endpoint():
    section("6. Health Endpoint - Route Declaration")
    urls_file = BACKEND / "sahara_gold" / "urls.py"
    if not urls_file.exists():
        fail("sahara_gold/urls.py not found"); return
    text = urls_file.read_text(encoding="utf-8")
    if "api/health/" in text: ok("/api/health/ route declared in urls.py")
    else: fail("/api/health/ route not declared - Render health check will fail")
    if "JsonResponse" in text and "health" in text: ok("Health endpoint returns JsonResponse")
    else: warn("Health endpoint may not return JSON - Render expects HTTP 200")


def print_summary():
    print(f"\n{'='*60}\n  PRODUCTION READINESS SUMMARY\n{'='*60}")
    if not failures and not warnings:
        print(f"\n  [PASS]  All checks passed! Ready for Render deployment.\n")
    else:
        if failures:
            print(f"\n  [FAIL]  {len(failures)} failure(s) - MUST fix before deploying:")
            for i, f in enumerate(failures, 1):
                print(f"      {i}. {f}")
        if warnings:
            print(f"\n  [WARN]  {len(warnings)} warning(s) - Review before deploying:")
            for i, w in enumerate(warnings, 1):
                print(f"      {i}. {w}")
        print()
    return len(failures)


def main():
    print("=" * 62)
    print("  Sahara Gold - Production Readiness Verification")
    print("  Target: Render Deployment (render.yaml Blueprint)")
    print("=" * 62)
    check_render_yaml()
    check_secret_hygiene()
    check_django_settings()
    check_frontend_build()
    check_build_script()
    check_health_endpoint()
    failure_count = print_summary()
    return 1 if failure_count else 0


if __name__ == "__main__":
    sys.exit(main())
