# Generated by Django 4.2.21 on 2026-09-14 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('service_selected', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('active', 'Active'), ('invoiced', 'Invoiced'), ('completed', 'Completed')], default='lead', max_length=20)),
                ('bot_enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('external_ids', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation_mode', models.CharField(choices=[('bot', 'Bot Handling'), ('pending', 'Pending Handoff'), ('agent', 'Agent Handling')], default='bot', max_length=10)),
                ('escalation_reason', models.CharField(blank=True, max_length=255)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('business_name', models.CharField(max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('logo', models.ImageField(blank=True, upload_to='tenant_logos/')),
                ('personality', models.CharField(choices=[('professional', 'Professional'), ('friendly', 'Friendly'), ('casual', 'Casual')], default='professional', max_length=20)),
                ('language', models.CharField(choices=[('auto', 'Auto-detect'), ('en', 'English'), ('bn', 'Bengali'), ('both', 'Bilingual (EN + BN)')], default='auto', max_length=10)),
                ('custom_rules', models.TextField(blank=True, help_text='Plain-text business rules for the AI')),
                ('escalation_rules', models.JSONField(blank=True, default=list)),
                ('llm_mode', models.CharField(choices=[('bundled', 'Bundled (GrownK LLM)'), ('byok', 'Bring Your Own Key')], default='bundled', max_length=20)),
                ('llm_api_key', models.TextField(blank=True, help_text='Customer API key (encrypted at rest)')),
                ('llm_model_name', models.CharField(default='Qwen/Qwen2.5-72B-Instruct', max_length=100)),
                ('wa_phone_number_id', models.CharField(blank=True, max_length=100)),
                ('wa_access_token', models.TextField(blank=True)),
                ('wa_webhook_token', models.CharField(blank=True, max_length=100)),
                ('wa_connected', models.BooleanField(default=False)),
                ('service_selected', models.CharField(blank=True, max_length=100)),
                ('external_ids', models.JSONField(blank=True, default=dict)),
                ('bot_enabled', models.BooleanField(default=True)),
                ('web_widget_enabled', models.BooleanField(default=True)),
                ('widget_color', models.CharField(default='#3B82F6', max_length=7)),
                ('widget_position', models.CharField(default='bottom-right', max_length=20)),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], default='starter', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_tenants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('member', 'Member')], default='member', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('url', 'Website URL'), ('file', 'Uploaded File'), ('manual', 'Manual Entry'), ('product_feed', 'Product Feed URL')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('raw_content', models.TextField(blank=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='knowledge_sources/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('chunk_count', models.IntegerField(default=0)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('auto_refresh', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_sources', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('vector_embedding', models.JSONField(blank=True, null=True)),
                ('char_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.knowledgesource')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_chunks', to='core.tenant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('items', models.JSONField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='BDT', max_length=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='draft', max_length=10)),
                ('pdf_path', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.client')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('web', 'Web Chat'), ('messenger', 'Facebook Messenger'), ('instagram', 'Instagram DM')], default='whatsapp', max_length=20)),
                ('message_text', models.TextField()),
                ('wa_message_id', models.CharField(blank=True, max_length=255)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.client')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.tenant')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.tenant'),
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('web', 'Web Chat'), ('messenger', 'Facebook Messenger'), ('instagram', 'Instagram DM')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_prompt', models.TextField(blank=True, help_text='Auto-generated system prompt (read-only preview)')),
                ('custom_prompt_override', models.TextField(blank=True, help_text='If set, replaces the auto-generated prompt entirely')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_config', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Bot Configuration',
            },
        ),
        migrations.CreateModel(
            name='BotAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(default='whatsapp', max_length=20)),
                ('user_message', models.TextField()),
                ('bot_reply', models.TextField()),
                ('intent', models.CharField(default='general', max_length=50)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=20)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('was_fallback', models.BooleanField(default=False)),
                ('was_escalated', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='core.client')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('agent', 'Agent')], default='agent', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tenant', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['slug'], name='tenant_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['owner'], name='tenant_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['is_active'], name='tenant_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.CheckConstraint(check=models.Q(('plan__in', ['starter', 'growth', 'enterprise'])), name='tenant_plan_valid'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(check=models.Q(('base_price__gte', 0)), name='service_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(check=models.Q(('subtotal__gte', 0)), name='invoice_subtotal_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(check=models.Q(('total_amount__gte', 0)), name='invoice_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['draft', 'sent', 'paid', 'overdue'])), name='invoice_status_valid'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['tenant', 'client', 'timestamp'], name='conv_tenant_client_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['wa_message_id'], name='conv_wamsgid_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['tenant', 'channel'], name='conv_tenant_channel_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['tenant', 'phone'], name='client_tenant_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['tenant', 'status'], name='client_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['tenant', 'conversation_mode'], name='client_tenant_mode_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['-created_at'], name='client_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['lead', 'active', 'invoiced', 'completed'])), name='client_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(check=models.Q(('conversation_mode__in', ['bot', 'pending', 'agent'])), name='client_mode_valid'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('tenant', 'phone')},
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('tenant', 'channel_type')},
        ),
        migrations.AddIndex(
            model_name='botanalytics',
            index=models.Index(fields=['tenant', '-created_at'], name='analytics_tenant_idx'),
        ),
        migrations.AddIndex(
            model_name='botanalytics',
            index=models.Index(fields=['tenant', 'intent'], name='analytics_tenant_intent_idx'),
        ),
        migrations.AddIndex(
            model_name='botanalytics',
            index=models.Index(fields=['tenant', 'channel'], name='analytics_tenant_channel_idx'),
        ),
        migrations.AddConstraint(
            model_name='botanalytics',
            constraint=models.CheckConstraint(check=models.Q(('response_time_ms__gte', 0)), name='analytics_resp_time_non_negative'),
        ),
    ]
