# Generated by Django 5.2.17 on 2026-09-15 18:49

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content'], name='knowledge_content_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
