# Generated by Django 4.2.30 on 2026-09-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_knowledgechunk_knowledge_content_trgm_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
